### ISSUE TITLE
클래스 이름은 대문자로 시작합니다

### ISSUE THREAD

**Issue by sigmadream** [goongju/ks-web#1]
https://github.com/goongju/ks-web/blob/085cbc40612f30deeb0cbdb6729463ea3841d083/src/main/java/com/jaeryeong/app/controller/indexController.java#L7

클래스 이름은 대문자로 시작해야 합니다

**Comment by goongju** [comment]
수정하였습니다!

**Comment by sigmadream** [comment]
감사합니다. :D
